ENVIRONMENTAL_ROLES = {

    "ENVIRONMENTAL_ENGINEER_ENTRY_LEVEL": {
        "ENVIRONMENTAL_ENGINEERING_FUNDAMENTALS": 5,
        "WATER_ENGINEERING": 4,
        "AIR_POLLUTION_CONTROL": 4,
        "SOIL_ENGINEERING": 4,
        "POLLUTION_CONTROL_TECHNOLOGIES": 5,
        "ENVIRONMENTAL_IMPACT_ASSESSMENT": 5,
        "ENVIRONMENTAL_MODELING": 4,
        "AUTOCAD": 3,
        "MATLAB": 3,
        "EXCEL": 3,
        "PROBLEM_SOLVING": 3,
        "TECHNICAL_REPORT_WRITING": 4,
        "TEAM_COLLABORATION": 2,
        "TIME_MANAGEMENT": 2
    },

    "WATER_RESOURCES_ENGINEER": {
        "HYDROLOGY": 5,
        "HYDRAULICS": 5,
        "WATER_TREATMENT": 5,
        "WASTEWATER_TREATMENT": 5,
        "PIPE_NETWORK_DESIGN": 4,
        "FLOOD_MODELING": 4,
        "WATERSHED_MANAGEMENT": 4,
        "EPANET": 4,
        "HEC_RAS": 4,
        "HEC_HMS": 4,
        "CIVIL_3D": 3,
        "ANALYTICAL_THINKING": 4,
        "PROJECT_COORDINATION": 3,
        "ATTENTION_TO_DETAIL": 3
    },

    "AIR_QUALITY_SPECIALIST": {
        "AIR_POLLUTION_CONTROL": 5,
        "EMISSION_MONITORING": 5,
        "AIR_DISPERSION_MODELING": 5,
        "AMBIENT_AIR_QUALITY_STANDARDS": 4,
        "AERMOD": 4,
        "CALPUFF": 4,
        "EXCEL": 3,
        "AIR_MONITORING_INSTRUMENTS": 4,
        "DATA_INTERPRETATION": 4,
        "FIELDWORK_READINESS": 3,
        "REGULATORY_AWARENESS": 4
    },

    "GEOTECHNICAL_CONTAMINATION_ENGINEER": {
        "SOIL_MECHANICS": 5,
        "GEOTECHNICAL_ENGINEERING": 5,
        "CONTAMINATED_LAND_ASSESSMENT": 5,
        "SITE_INVESTIGATION": 4,
        "REMEDIATION_TECHNOLOGIES": 4,
        "PLAXIS": 4,
        "GEOSTUDIO": 4,
        "GIS": 3,
        "FIELD_TESTING": 4,
        "SAFETY_AWARENESS": 3,
        "TECHNICAL_DOCUMENTATION": 4,
        "OBSERVATION_SKILLS": 3
    },

    "SUSTAINABILITY_GREEN_BUILDING_CONSULTANT": {
        "SUSTAINABLE_DESIGN": 5,
        "ENERGY_EFFICIENCY_ANALYSIS": 5,
        "LIFE_CYCLE_ASSESSMENT": 5,
        "CARBON_FOOTPRINT_ANALYSIS": 5,
        "LEED_CERTIFICATION": 4,
        "GRI_STANDARDS": 3,
        "ISO_14001": 4,
        "CLIENT_COMMUNICATION": 3,
        "PRESENTATION_SKILLS": 3,
        "STRATEGIC_THINKING": 4
    },

    "ENVIRONMENTAL_ANALYST": {
        "ENVIRONMENTAL_DATA_ANALYSIS": 5,
        "IMPACT_ASSESSMENT": 5,
        "STATISTICAL_ANALYSIS": 4,
        "SAMPLING_METHODS": 4,
        "LABORATORY_METHODS": 4,
        "EXCEL": 4,
        "SPSS": 3,
        "R_PROGRAMMING": 4,
        "GIS": 4,
        "CRITICAL_THINKING": 4,
        "RESEARCH_SKILLS": 4,
        "WRITTEN_COMMUNICATION": 4
    },

    "REGULATORY_COMPLIANCE_SPECIALIST": {
        "ENVIRONMENTAL_LAWS": 5,
        "ENVIRONMENTAL_REGULATIONS": 5,
        "ENVIRONMENTAL_AUDITING": 5,
        "PERMIT_DOCUMENTATION": 4,
        "RISK_ASSESSMENT": 4,
        "ISO_14001": 4,
        "OSHA_BASICS": 4,
        "COMPLIANCE_MANAGEMENT": 5,
        "ATTENTION_TO_DETAIL": 4,
        "ETHICAL_RESPONSIBILITY": 4,
        "DOCUMENTATION_SKILLS": 4
    },

    "GIS_ANALYST": {
        "SPATIAL_DATA_ANALYSIS": 5,
        "REMOTE_SENSING": 4,
        "ENVIRONMENTAL_MAPPING": 5,
        "DATABASE_MANAGEMENT": 4,
        "ARCGIS": 5,
        "QGIS": 5,
        "ERDAS_IMAGINE": 3,
        "GPS_TOOLS": 3,
        "DATA_VISUALIZATION": 4,
        "ANALYTICAL_REASONING": 4,
        "PRECISION": 3
    },

    "ENVIRONMENTAL_FIELD_TECHNICIAN": {
        "WATER_SAMPLING": 5,
        "AIR_SAMPLING": 5,
        "SOIL_SAMPLING": 5,
        "FIELD_TESTING_METHODS": 4,
        "EQUIPMENT_CALIBRATION": 4,
        "LAB_PROCEDURES": 4,
        "SAMPLING_KITS": 3,
        "PORTABLE_ANALYZERS": 3,
        "GPS_DEVICES": 3,
        "SAFETY_COMPLIANCE": 4,
        "FIELD_DOCUMENTATION": 4,
        "PHYSICAL_ENDURANCE": 2
    },

    "WASTE_MANAGEMENT_COORDINATOR": {
        "SOLID_WASTE_MANAGEMENT": 5,
        "HAZARDOUS_WASTE_MANAGEMENT": 5,
        "RECYCLING_TECHNOLOGIES": 4,
        "WASTE_AUDIT": 4,
        "PROCESS_OPTIMIZATION": 4,
        "EXCEL": 3,
        "INVENTORY_SYSTEMS": 3,
        "STAKEHOLDER_COMMUNICATION": 3,
        "ORGANIZATIONAL_SKILLS": 3,
        "COST_EFFICIENCY": 4
    }

}